# Generated by Django 6.0 on 2025-12-11 20:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('giro', models.CharField(max_length=200, verbose_name='Giro Comercial')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Equipo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Equipo')),
                ('tipo', models.CharField(choices=[('MAQ', 'Máquina'), ('EQU', 'Equipo Electrónico'), ('SIS', 'Sistema'), ('VEH', 'Vehículo'), ('OTR', 'Otro')], default='MAQ', max_length=3, verbose_name='Tipo de Equipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('fecha_instalacion', models.DateField(verbose_name='Fecha de Instalación')),
                ('ubicacion', models.CharField(max_length=300, verbose_name='Ubicación Física')),
                ('ficha_tecnica', models.TextField(blank=True, verbose_name='Ficha Técnica')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='api.cliente', verbose_name='Cliente Dueño')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PlanMantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('frecuencia', models.CharField(choices=[('DIA', 'Diaria'), ('SEM', 'Semanal'), ('MEN', 'Mensual'), ('BIM', 'Bimestral'), ('TRI', 'Trimestral'), ('SEM', 'Semestral'), ('ANU', 'Anual')], default='MEN', max_length=3, verbose_name='Frecuencia')),
                ('duracion_estimada', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración Estimada (horas)')),
                ('procedimiento', models.TextField(verbose_name='Procedimiento a Seguir')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantencion', to='api.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Plan de Mantención',
                'verbose_name_plural': 'Planes de Mantención',
                'ordering': ['equipo', 'nombre'],
                'unique_together': {('equipo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('especialidad', models.CharField(choices=[('MEC', 'Mecánico'), ('ELE', 'Eléctrico'), ('ELE', 'Electrónico'), ('SIS', 'Sistemas'), ('GEN', 'General')], default='GEN', max_length=3, verbose_name='Especialidad')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de Contratación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Orden')),
                ('descripcion', models.TextField(verbose_name='Descripción del Trabajo')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio Real')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin Real')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'En Proceso'), ('FIN', 'Finalizada'), ('CAN', 'Cancelada')], default='PEN', max_length=3, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJ', 'Baja'), ('MED', 'Media'), ('ALT', 'Alta'), ('URG', 'Urgente')], default='MED', max_length=3, verbose_name='Prioridad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Estimado')),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Real')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='api.equipo', verbose_name='Equipo')),
                ('plan_mantencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='api.planmantencion', verbose_name='Plan de Mantención Asociado')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='api.tecnico', verbose_name='Técnico Asignado')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
